package exception_handling;
/*
public class ExceptionHandling6 {

	public static void main(String[] args) {
		 
		System.out.println("Program starts");
		int[] num=new int[3];
		try {
			System.out.println(num[3]);
		}catch(Throwable e) {
			System.out.println("Exception found and handled");
		}catch(ArithmeticException e) {//unreachable block
			System.out.println("Exception found and handled");
		}catch(ArrayIndexOutOfBoundsException e) {//unreachable block
			System.out.println("Exception found and handled");
		}catch(Exception e) {//unreachable block
			System.out.println("Exception found and handled");
		}
		System.out.println("Program ends");
	}

}
*/